[package]
name = "command_tool"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.67", features = ["full"] }

[dev-dependencies]
clap = "4.5.40"
log = "0.4.27"
